Numpy is nothing but Numerical Python.

*   Numpy is used to convert normal data into dimensional data.





In Numpy :

1.   axis = 1 refers "Rows"
2.   axis = 0 refers "Columns"
3.   axis = None converts into 1D array.





In [1]:
import numpy as np
# Creating an array;
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
a = np.array((1,2,3,4,5))
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# Creating an array using arange function;
a = np.arange(1,11)
print(a)
print(type(a))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [ ]:
b = np.linspace(1,15,5)
print(b)

[ 1.   4.5  8.  11.5 15. ]


In [ ]:
a = np.arange(11,21)
print(a.ndim)
print(a.shape)

1
(10,)


In [ ]:
a = np.arange(1,13)
b = a.reshape(3,2,2)
print(b)
print(b.shape)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
(3, 2, 2)


In [ ]:
print(b[2][1][1])
print(b.size)

12
12


In [ ]:
a = np.array((1,2,3,4,5))
print(a)
print(a.shape)
b = a.reshape(1,-1)
print(b)
print(b.shape)

[1 2 3 4 5]
(5,)
[[1 2 3 4 5]]
(1, 5)


In [ ]:
a = np.arange(1,10).reshape(3,3)
print(a)
b = a.transpose()
print(b)
c = b.transpose()
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
d = []
for i in a :
  row = []
  for j in range(len(i)) :
    row.append(i[len(i)-j-1])
  d.append(row)
e = np.array(d)
print(e)
print(e.transpose())

[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[3 6 9]
 [2 5 8]
 [1 4 7]]


In [ ]:
d = []
for i in range(len(a)-1,-1,-1) :
  row = []
  for j in range(len(a[i])) :
    row.append(a[i][i-j])
  d.append(row)
print(np.array(d))
print(a)

[[9 8 7]
 [5 4 6]
 [1 3 2]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
m = np.ones((3,3),int)
print(m)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
a = np.zeros((2,3),int)
print(a)

[[0 0 0]
 [0 0 0]]


In [ ]:
a = np.eye(3,dtype = int)
print(a)
print(a.diagonal())

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[1 1 1]


In [ ]:
a = np.full((3,3),5)
print(a)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [ ]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = a.T
print(b)

[[1 3]
 [2 4]]


In [ ]:
a = np.array([[1,2],[3,4]])
b = a.ravel()
print(b)

[1 2 3 4]


In [ ]:
a = np.array([[1,2],[3,4],[5,6],[7,8]])
b = np.array([[11,12,13],[14,15,16]])
c = np.concatenate((a,b),axis = None)
print(c.ndim)
print(c.shape)

1
(14,)


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
b = np.sum(a,axis = 0)
print(b)
print(b.ndim)
print(b.shape)

[5 7 9]
1
(3,)


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print('***************')
b = np.max(a,axis = 0)
print(f'max value from each column >> {b}') # Because axis = 0
print(b.ndim)
print(b.shape)

[[1 2 3]
 [4 5 6]]
***************
max value from each column >> [4 5 6]
1
(3,)


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print('***************')
b = np.max(a,axis = 1)
print(f'max value from each row >> {b}') # Because axis = 1
print(b.ndim)
print(b.shape)

[[1 2 3]
 [4 5 6]]
***************
max value from each column >> [3 6]
1
(2,)


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print('***************')
b = np.max(a)
print(f'max value from whole array >> {b}') # Because by default axis = None
print(b.ndim)
print(b.shape)

[[1 2 3]
 [4 5 6]]
***************
max value from whole array >> 6
0
()


In [ ]:
# argmax()  and  argmin() ;
a = np.array([[12,3,15,7],[35,21,7,8],[4,9,32,11]])
print(a)
print('**********************')
print(f'index of max value from whole array > {np.argmax(a,axis=None)}')  # axis = None
print(f'index of min value from whole array > {np.argmin(a,axis=None)}')

[[12  3 15  7]
 [35 21  7  8]
 [ 4  9 32 11]]
**********************
index of max value from whole array > 4
index of min value from whole array > 1


In [ ]:
# argmax()  and  argmin() ;
a = np.array([[12,3,15,7],[35,21,7,8],[4,9,32,11]])
print(a)
print('**********************')
print(f'index of max value from each row > {np.argmax(a,axis=1)}')  # axis = 1 ==>> row wise operation
print(f'index of min value from each row > {np.argmin(a,axis=1)}')

[[12  3 15  7]
 [35 21  7  8]
 [ 4  9 32 11]]
**********************
index of max value from each row > [2 0 2]
index of min value from each row > [1 2 0]


In [ ]:
# argmax()  and  argmin() ;
a = np.array([[12,3,15,7],[35,21,7,8],[4,9,32,11]])
print(a)
print('**********************')
print(f'index of max value from each column > {np.argmax(a,axis=0)}')  # axis = 0 ==>> column wise operation
print(f'index of min value from each column > {np.argmin(a,axis=0)}')

[[12  3 15  7]
 [35 21  7  8]
 [ 4  9 32 11]]
**********************
index of max value from each column > [1 1 2 2]
index of min value from each column > [2 0 1 0]


In [ ]:
a = np.array([[12,3,15,7],[35,21,7,8],[4,9,32,11]])
np.split(a,[3, 5, 6, 10])

[array([[12,  3, 15,  7],
        [35, 21,  7,  8],
        [ 4,  9, 32, 11]]),
 array([], shape=(0, 4), dtype=int64),
 array([], shape=(0, 4), dtype=int64),
 array([], shape=(0, 4), dtype=int64),
 array([], shape=(0, 4), dtype=int64)]

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [9]:
# dot() function.
a = np.array([[1,2],[3,4],[11,12]])
b = np.array([[5,6,7],[1,2,3]])   # no of columns of 'a' == no fo rows of 'b'
c = np.dot(a,b)
print(c)

[[  7  10  13]
 [ 19  26  33]
 [ 67  90 113]]


In [12]:
# randint
a = np.random.randint(10,30,5)
a

array([26, 14, 16, 12, 10])

In [34]:
a = np.random.randn(2,3)
a

array([[ 0.47351282, -0.84813793, -1.45255526],
       [-0.05562054,  0.29419274,  1.14959833]])

In [35]:
a = np.random.rand(2,3)
a

array([[0.08144145, 0.1808719 , 0.56987059],
       [0.25788485, 0.58038269, 0.14016154]])

In [37]:
a = np.random.random()
a

0.6280723458808454

In [42]:
# Mean
a = np.array([[5,3],[8,2]])
b = np.mean(a)
print(b)
c = np.mean(a,axis=1)
c

4.5


array([4., 5.])

In [44]:
# Median
a = np.array([[5,3],[8,2]])
b = np.median(a)
print(b)
c = np.median(a,axis=0)
c

4.0


array([6.5, 2.5])

In [48]:
# std()  Standard Deviation.
a = np.array([[5,3],[8,2]])
print(np.std(a))  # it converts into 1D and gives the S.D of all the elements
print(np.std(a,axis = 1))  # it performs row operation and returns the S.D of each row.
print(np.std(a,axis = 0))  # it performs column operation and returns the S.D of each column.


2.29128784747792
[1. 3.]
[1.5 0.5]


In [53]:
# sqrt  Square Root.
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np.sqrt(a))

[[1.         1.41421356 1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712 3.         3.16227766]]


In [56]:
# exp()  Exponent.
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np.exp(b))

[[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
  1.48413159e+02]
 [4.03428793e+02 1.09663316e+03 2.98095799e+03 8.10308393e+03
  2.20264658e+04]]


In [58]:
# log()
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np.log(b))

[[0.         0.69314718 1.09861229 1.38629436 1.60943791]
 [1.79175947 1.94591015 2.07944154 2.19722458 2.30258509]]


In [60]:
# where()
arr = np.array([[-2,3,1,-5],[7,-9,4,-6]])
np.where(arr > 0, 1, 0)

array([[0, 1, 1, 0],
       [1, 0, 1, 0]])

In [64]:
# updating Even values with *10 and Odd values with *5 with using where().
a = np.arange(1,11)
np.where(a%2 == 0 , a*10,a*5)

array([  5,  20,  15,  40,  25,  60,  35,  80,  45, 100])