In [1]:
import numpy as np

In [6]:
a = np.arange(1,10)
print(a)
print(a.shape)
print(a.ndim)
print(a.size)

[1 2 3 4 5 6 7 8 9]
(9,)
1
9


In [9]:
b = a.reshape(3,3)
print(b)
print(b.shape)
print(b.ndim)
print(b.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2
9


In [19]:
c = b[:,::-1]
print(c)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [21]:
d = np.where(c%2 == 0 , 0,1)
d

array([[1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]])

In [23]:
print(np.where(d == 0 , "Zero","One"))

[['One' 'Zero' 'One']
 ['Zero' 'One' 'Zero']
 ['One' 'Zero' 'One']]


In [5]:
a = np.random.randint(1,19,15)
print(a)
print(a[5])
print(a[10])

[14 18  4  3  8  9  7 18  3  5 14 11  6  1 17]
9
14


In [7]:
from os import kill
a = np.arange(1,15)
k = 3
for i in range(len(a)-(k+1)) :
  print((a[i:i+k]))


[1 2 3]
[2 3 4]
[3 4 5]
[4 5 6]
[5 6 7]
[6 7 8]
[7 8 9]
[ 8  9 10]
[ 9 10 11]
[10 11 12]


In [27]:
a = np.arange(1,17).reshape(4,4)
b = a[:2,2:]
print(b)

[[3 4]
 [7 8]]


In [28]:
a = np.random.randint(10,50,4*5).reshape(4,5)
print(a)

[[47 27 27 43 34]
 [17 40 43 17 13]
 [18 15 38 43 49]
 [23 23 30 15 13]]


In [29]:
b = a.T
print(b)

[[47 17 18 23]
 [27 40 15 23]
 [27 43 38 30]
 [43 17 43 15]
 [34 13 49 13]]


In [30]:
a = np.random.randint(1,100,20)
print(max(a))
print(min(a))


94
1


In [36]:
a = np.random.randint(1,10,6).reshape(2,3)
b = np.random.randint(1,15,6).reshape(3,2)

c = np.dot(a,b)
print(c)

[[134 188]
 [ 97 179]]


In [34]:
a = np.random.randint(1,50,5*5).reshape(5,5)
print(a)
print(np.mean(a))
print(np.std(a))
print(np.var(a))

[[13 22  5 35 27]
 [43 26 34 33 48]
 [39 45 21 44  5]
 [37 20 32  5 16]
 [ 4 29 30 14 45]]
26.88
13.627384195068398
185.70559999999998


In [37]:
a = np.random.randint(1,50,5*5).reshape(5,5)
b = np.arange(1,6)
print(a+b)

[[40  6 50 47  7]
 [42 18 49 51 27]
 [24 16 17 33 43]
 [35 46 40 33 34]
 [29 34 35 24 54]]


In [38]:
a = np.random.randint(1,100,10)
print(a[[2,5,8]])

[57 43 94]


In [40]:
a = np.arange(1,10).reshape(3,3)
print(a)
print(np.linalg.det(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
0.0


In [42]:
a = np.random.randint(1,20,9)
print(sorted(a))

[4, 8, 8, 11, 11, 13, 15, 16, 18]


In [51]:
a = np.random.randint(1,50,9).reshape(3,3)
np.where(a > 30 , 0,a)

array([[ 6, 21, 14],
       [ 0,  0, 14],
       [16,  0,  0]])